theme: jekyll-theme-cayman
title: Self-supervised Multi-scale Consistency for Weakly Supervised Segmentation Learning
description: Gabriele Valvano, Andrea Leo, Sotirios A. Tsaftaris
google_analytics: G-TSC2WQC7ZM
show_downloads: true
button_home_url: index
button_paper_url: https://arxiv.org/abs/2108.11900
button_code_url: https://github.com/gvalvano/multiscale-pyag
button_contacts_url: contacts
banner: https://github.com/vios-s/multiscale-pyag/blob/main/images/banner.pdf
plugins:
  - jemoji
image_url_prefix: images
